# Generated by Django 5.1.7 on 2025-04-08 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
